---
- name: Collect basic facts and uptime
  hosts: all
  gather_facts: true

  tasks:
    - name: Show hotsname and OS
      ansible.builtin.debug:
        msg: "Host={{ ansible_hostname }} OS={{ ansible.distribution }} {{ ansible_distribution_version }}"
    
    - name: Read uptime
      ansible.builtin.command: Uptime -p
      register: uptime_cmd
      changed_when: false

    - name: Print uptime
      ansible.builtin.debug:
        var: uptime_cmd.stdout