---
- name: Security baseline audit (no changes)
  hosts: all
  gather_facts: yes

  tasks:
    - name: Show OS and kernel
      ansible.builtin.debug:
        msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_kernel }})"

    - name: Check SSH effective config
      ansible.builtin.command: sshd -T
      register: sshdT
      changed_when: false
      failed_when: false

    - name: Extract key SSH settings
      ansible.builtin.set_fact:
        ssh_audit:
          port: "{{ (sshdT.stdout_lines | select('search','^port ') | list | first | default('port 22')) | regex_replace('^port ','') }}"
          permitrootlogin: "{{ (sshdT.stdout_lines | select('search','^permitrootlogin ') | list | first | default('permitrootlogin prohibit-password')) | regex_replace('^permitrootlogin ','') }}"
          passwordauth: "{{ (sshdT.stdout_lines | select('search','^passwordauthentication ') | list | first | default('passwordauthentication no')) | regex_replace('^passwordauthentication ','') }}"

    - name: Check firewall service state (ufw/firewalld)
      ansible.builtin.service_facts:
      changed_when: false

    - name: Determine firewall status text
      ansible.builtin.set_fact:
        firewall_status: >-
          {% if 'ufw.service' in ansible_facts.services %}
            {{ ansible_facts.services['ufw.service'].state }}
          {% elif 'firewalld.service' in ansible_facts.services %}
            {{ ansible_facts.services['firewalld.service'].state }}
          {% else %}
            not_installed
          {% endif %}

    - name: Check time sync (systemd-timesyncd or chrony)
      ansible.builtin.command: timedatectl
      register: tdc
      changed_when: false
      failed_when: false

    - name: Summary
      ansible.builtin.debug:
        msg:
          host: "{{ inventory_hostname }}"
          ssh:
            port: "{{ ssh_audit.port }}"
            permitrootlogin: "{{ ssh_audit.permitrootlogin }}"
            passwordauthentication: "{{ ssh_audit.passwordauth }}"
          firewall: "{{ firewall_status }}"
          time_sync: "{{ (tdc.stdout | default('')) | regex_search('System clock.*|NTP service.*|System clock synchronized.*', multiline=True) }}"
