---
- name: System info (safe + fast)
  hosts: all
  gather_facts: no

  tasks:
    - name: Gather minimal facts (skip mounts)
      ansible.builtin.setup:
        gather_subset:
          - min
          - "!mounts"

    - name: Show OS and kernel
      ansible.builtin.debug:
        msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} ({{ ansible_kernel }})"

    - name: Show root filesystem usage only
      ansible.builtin.command: df -h /
      register: disk
      changed_when: false
      failed_when: disk.rc != 0

    - name: Print disk usage
      ansible.builtin.debug:
        var: disk.stdout_lines
